compile:  

	g++ region.cpp ../core/Message.h ../core/Message.cpp ../core/Configuration.h ../core/Configuration.cpp ../core/BaseNet.h ../core/BaseNet.cpp ../core/MessageConfig.h ../core/MessageDelivery.h ../core/MessageDelivery.cpp ../core/Publisher.h ../core/Publisher.cpp ../core/Subscriber.h ../core/Subscriber.cpp ../core/Subscription.h ../core/Subscription.cpp RegionMessageDelivery.h RegionMessageDelivery.cpp AvatarNpcManager.h AvatarNpcManager.cpp -pthread -o region
clean:
	rm region
