compile:  

	g++ server.cpp Modules.h Modules.cpp core/Message.h core/Message.cpp core/Configuration.h core/Configuration.cpp core/BaseNet.h core/BaseNet.cpp core/MessageConfig.h core/MessageDelivery.h core/MessageDelivery.cpp core/Publisher.h core/Publisher.cpp core/Subscriber.h core/Subscriber.cpp core/Subscription.h core/Subscription.cpp core/CharacterListMessage.h core/CharacterListMessage.cpp core/LoginMessage.h core/LoginMessage.cpp -pthread -o server

clean:
	rm server

# core/MessageDelivery.h core/MessageDelivery.cpp
#core/Publisher.h core/Publisher.cpp core/Subscriber.h core/Subscriber.cpp
