#ifndef _NIX_MESSAGECONFIG
#define _NIX_MESSAGECONFIG

enum MESSAGE_DESTINATION
{
	MESSAGE_DESTINATION_CHAT,
	MESSAGE_DESTINATION_LOGIN,
	MESSAGE_DESTINATION_CREATION,
	MESSAGE_DESTINATION_REGION,
	MESSAGE_DESTINATION_CENTRAL
};

enum MESSAGE_OPTIONS_CENTRAL
{
	MESSAGE_OPTIONS_CENTRAL_LOGIN,
	MESSAGE_OPTIONS_CENTRAL_CHARACTERLIST
};

enum MESSAGE_OPTIONS_REGION
{
	MESSAGE_OPTIONS_REGION_AVATAR_NPC_MANAGER
};

enum MESSAGE_FUNCTION_AVATARNPCMANAGER
{
	MESSAGE_FUNCTION_AVATARNPCMANAGER_NEW_CONNECTION
};

enum MESSAGE_OPTIONS_CACHE
{
	MESSAGE_OPTIONS_CACHE_LOGIN
};

enum MESSAGE_FUNCTION_CACHE_LOGIN
{
	MESSAGE_FUNCTION_CACHE_LOGIN_NEW_CONNECTION,
	MESSAGE_FUNCTION_CACHE_LOGIN_USERNAME,
	MESSAGE_FUNCTION_CACHE_LOGIN_PASSWORD
};


#endif
