compile:  

	g++ db.cpp DataBase.h DataBase.cpp mysql_connection.h mysql_driver.h cppconn/build_config.h cppconn/config.h cppconn/datatype.h cppconn/driver.h cppconn/exception.h cppconn/metadata.h cppconn/parameter_metadata.h cppconn/prepared_statement.h cppconn/resultset.h cppconn/resultset_metadata.h cppconn/sqlstring.h cppconn/statement.h cppconn/warning.h cppconn/connection.h ../core/Configuration.h ../core/Configuration.cpp -Iinclude -Llib -L/usr/lib64/mysql -lmysqlclient  -o db

clean:
	rm db

# core/MessageDelivery.h core/MessageDelivery.cpp
#core/Publisher.h core/Publisher.cpp core/Subscriber.h core/Subscriber.cpplibmysqlcppconn-static
